name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  on-pull-request:
    name: test
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          
      - name: Print node verstion
        run: node -v
        
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
